# Generated by Django 4.1.2 on 2022-11-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pelicula', models.CharField(max_length=50)),
                ('resumen', models.TextField(max_length=300)),
                ('genero', models.CharField(max_length=20)),
                ('duracion', models.PositiveIntegerField()),
                ('reparto', models.CharField(max_length=50)),
            ],
        ),
    ]
